/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.8/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    id("java");
}
val allureVersion = "2.25.0"
group = "com.reqres"

repositories {
    mavenCentral()
}

dependencies {
    // Rest Assured
    implementation("io.rest-assured:rest-assured:5.5.2"); //add rest-assured dependencies
    implementation("org.testng:testng:7.9.0"); //add testng dependencies
    //implementation(libs.testng); //add testng dependencies
    implementation("io.rest-assured:json-path:5.5.2"); //add rest-assured json path
    //implementation(libs.guava) // This dependency is used by the application.
    implementation(platform("io.qameta.allure:allure-bom:$allureVersion"))// Import allure-bom to ensure correct versions of all the dependencies are used
    implementation("io.qameta.allure:allure-rest-assured")// Add necessary Allure dependencies to dependencies section
    implementation("io.qameta.allure:allure-testng")// Add necessary Allure dependencies to dependencies section

    // JSON manipulation
    implementation("org.json:json:20230227")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.test {
    useTestNG()
}