/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.8/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    java
}

group = "com.reqres"

repositories {
    mavenCentral()
}

dependencies {
    // Rest Assured
    implementation("io.rest-assured:rest-assured:5.5.2"); //add rest-assured dependencies
    implementation("org.testng:testng:7.9.0"); //add testng dependencies
    //implementation(libs.testng); //add testng dependencies
    implementation("io.rest-assured:json-path:5.5.2"); //add rest-assured json path
    //implementation(libs.guava) // This dependency is used by the application.
    // JSON manipulation
    implementation("org.json:json:20230227")
    
    // TestNG
    testImplementation("org.testng:testng:7.7.1")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.test {
    useTestNG()
}