/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.8/userguide/building_java_projects.html in the Gradle documentation.
 */


val allureVersion = "2.24.0"
val restAssuredVersion = "5.5.2"
val slf4jVersion = "2.0.7"
val testngVersion = "7.9.0"
val jsonVersion = "20230227"
val javaVersion = "21"

plugins {
    id("java")
    id("io.qameta.allure") version "2.11.2"
}

group = "com.reqres"

repositories {
    mavenCentral()
}

dependencies {
    implementation("io.rest-assured:rest-assured:$restAssuredVersion") //add rest-assured dependencies
    implementation("org.testng:testng:$testngVersion") //add testng dependencies
    //implementation(libs.testng); //add testng dependencies
    implementation("io.rest-assured:json-path:$restAssuredVersion") //add rest-assured json path
    //implementation(libs.guava) // This dependency is used by the application.
    implementation("io.qameta.allure:allure-rest-assured:$allureVersion")// Add necessary Allure dependencies to dependencies section
    implementation("io.qameta.allure:allure-testng:$allureVersion")// Add necessary Allure dependencies to dependencies section
    implementation("org.json:json:$jsonVersion")// JSON manipulation
    implementation("org.slf4j:slf4j-api:$slf4jVersion")// Logging
    implementation("org.slf4j:slf4j-simple:$slf4jVersion")// Logging
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(javaVersion)
    }
}

tasks.test {
    useTestNG(){
        suites("src/test/resources/testng.xml")
        systemProperties = mapOf(
            "allure.results.directory" to "${project.buildDir}/allure-results"
        )
    }
    // Configure Allure report generation
    finalizedBy("allureReport")
}

allure {
    version.set(allureVersion)
    adapter {
        aspectjWeaver.set(true)
        frameworks {
            testng {
                enabled.set(true)
            }
        }
    }
}