name: ReqRes API Tests

on:
  #schedule:
    # Schedule to run 8 times a day at specific hours in UTC+2
    #- cron: '0 0,3,6,9,12,15,18,21 * * *'
  push:
    branches: 
      - main

jobs:
  Run-Rest-Assured-Tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 #
      
    - name: Build and Run REST Assured Tests with TestNG
      run: make .PHONY
      
    - name: Archive REST-Assured results
      uses: actions/upload-artifact@v4
      with:
        name: REST-Assured-results
        path: target/assured-reports

    - name: Upload REST-Assured results to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: REST-Assured-results
        path: target/assured-reports